server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  #MQ配置信息
#  rabbitmq:
#    host: 192.168.1.253
#    port: 5672
#    username: ybadmin
#    password: ybadmin123
#    virtual-host: /
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: yb
    password: yb123456
    virtual-host: /
    #确认消息已发送到交换机(Exchange)
    #publisher-confirms: true
#    publisher-confirm-type: correlated
#    #确认消息已发送到队列(Queue)
#    publisher-returns: true
